### ISSUE TITLE
access error 

### ISSUE THREAD

**Issue by oluies** [hortonworks-gallery/ambari-zeppelin-service#15]
Environment
14.04.1-Ubuntu
HDP-2.3.4.0-3485

I am getting the follwing access error when running install, looks like access rights on  `/var/log/zeppelin/zeppelin-setup.log'`

```
ls -al /var/log/zeppelin
total 8
drwxr-xr-x  2 zeppelin zeppelin 4096 Feb 24 12:47 .
drwxrwxr-x 36 root     syslog   4096 Feb 24 12:47 ..
-rw-r--r--  1 zeppelin zeppelin    0 Feb 24 12:47 zeppelin-setup.log
```

```
<script id="metamorph-12336-start" type="text/x-placeholder"></script>Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.3/services/ZEPPELIN/package/scripts/master.py", line 301, in <module>
    Master().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 219, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.3/services/ZEPPELIN/package/scripts/master.py", line 58, in install
    Execute('echo spark_version:' + params.spark_version + ' detected for spark_home: ' + params.spark_home + ' >> ' + params.zeppelin_log_file)
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 154, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 158, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 121, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 238, in action_run
    tries=self.resource.tries, try_sleep=self.resource.try_sleep)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 70, in inner
    result = function(command, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 92, in checked_call
    tries=tries, try_sleep=try_sleep)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 140, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 291, in _call
    raise Fail(err_msg)
```

```
2016-02-24 12:47:51,605 - File['/var/log/zeppelin/zeppelin-setup.log'] {'content': '', 'owner': 'zeppelin', 'group': 'zeppelin', 'mode': 0644}
2016-02-24 12:47:51,638 - Writing File['/var/log/zeppelin/zeppelin-setup.log'] because it doesn't exist
2016-02-24 12:47:51,661 - Changing owner for /var/log/zeppelin/zeppelin-setup.log from 0 to zeppelin
2016-02-24 12:47:51,662 - Changing group for /var/log/zeppelin/zeppelin-setup.log from 0 to zeppelin
2016-02-24 12:47:51,684 - Execute['echo spark_version:1.5 detected for spark_home: /usr/hdp/current/spark-client/ >> /var/log/zeppelin/zeppelin-setup.log'] {}<script id="metamorph-12338-end" type="text/x-placeholder"></script>
```

**Comment by oluies** [comment]
Workaround : chmod 777 /var/log/zeppelin/zeppelin-setup.log /var/log/zeppelin/

**Comment by abajwa-hw** [comment]
Thanks. Thats strange because these lines in the code are supposed to ensure the log dirs and log file are created with the right permissions
https://github.com/hortonworks-gallery/ambari-zeppelin-service/blob/master/package/scripts/master.py#L44-L56

**Comment by oluies** [comment]
Yes, I saw that, and the process is executed as root?

**Comment by abajwa-hw** [comment]
Yes as part of my testing on RHEL/CentOS those steps worked ok so I assume its running as root

**Comment by oluies** [comment]
Will this service work with 2.4? I can try to reinstall on a new cluster ?

**Comment by oluies** [comment]
Sorry I now see in the Readme that Zeppelin is included as a "Tech	Preview	Packages"

**Comment by abajwa-hw** [comment]
@oluies the service has been updated to deploy Zeppelin 0.5.6 on HDP 2.4
However as you mentioned it is still "Tech preview"

**Comment by oluies** [comment]
@abajwa-hw thanks closing this 

Started install but stuck here 
https://community.hortonworks.com/questions/21166/hdp-24-upgrade-found-service-components-in-install.html
