### ISSUE TITLE
Suse Linux Enterprise 11.4 - gfo

### ISSUE THREAD

**Issue by denicc** [hortonworks-gallery/ambari-zeppelin-service#19]
Hey guys,

can you help me with this ?
gcc-gfortran cannot be found. Is it a problem of a metainfo.xml dependency? (In Suse Linux the package is called gcc-fortran and not gcc-gfortran)

Thank you for helping!

---------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.3/services/ZEPPELIN/package/scripts/master.py", line 235, in <module>
    Master().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 216, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.3/services/ZEPPELIN/package/scripts/master.py", line 54, in install
    self.install_packages(env)
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 392, in install_packages
    Package(name)
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 154, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 152, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 118, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/__init__.py", line 45, in action_install
    self.install_package(package_name, self.resource.use_repos, self.resource.skip_repos)
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/package/zypper.py", line 70, in install_package
    shell.checked_call(cmd, sudo=True, logoutput=self.get_logoutput())
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 70, in inner
    result = function(command, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 92, in checked_call
    tries=tries, try_sleep=try_sleep)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 140, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 291, in _call
    raise Fail(err_msg)
resource_management.core.exceptions.Fail: Execution of '/usr/bin/zypper --quiet install --auto-agree-with-licenses --no-confirm gcc-gfortran' returned 104. Package 'gcc-gfortran' not found.

**Comment by martinasek** [comment]
Hello,

same issue here.When i try to install via zypper : 

```
zypper install gcc-fortran
Retrieving repository 'suse' metadata [done]
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides gcc43 = 4.3.3_20081022-11.18 needed by gcc43-fortran-4.3.3_20081022-11.18.x86_64
 Solution 1: do not install gcc-fortran-4.3-62.198.x86_64
 Solution 2: break gcc43-fortran-4.3.3_20081022-11.18.x86_64 by ignoring some of its dependencies
```
So  when i list gcc-43 installed version : 

```
zypper wp gcc43
Retrieving repository 'suse' metadata [done]
Loading repository data...
Reading installed packages...
S | Name  | Type    | Version                | Arch   | Repository
--+-------+---------+------------------------+--------+------------------
i | gcc43 | package | 4.3.4_20091019-0.37.30 | x86_64 | (System Packages)
```
This means there is a newer version of gcc43  - 4.3.4 already installed.

**Comment by martinasek** [comment]
Hey guys, pls take a look here where im solving similar problem :+1: 

https://issues.apache.org/jira/browse/AMBARI-15659

Additionaly I believe there is no such a package in SLES such as **gcc-gfortran**.The package name in SUSE  is **gcc-fortran** ??
