### ISSUE TITLE
This version is not compatble with ambari 2.2 with spark 1.2 on ubuntu 12

### ISSUE THREAD

**Issue by Ngalstyan4** [hortonworks-gallery/ambari-zeppelin-service#2]
I keep getting an error about missing or erroneous repository xml files

**Comment by Ngalstyan4** [comment]
![temp](https://cloud.githubusercontent.com/assets/4647374/8852532/d26e0e32-3166-11e5-8b05-73b23355d0a6.PNG)

**Comment by abajwa-hw** [comment]
Thanks! Pushed an update to add support for spark 1.2. Also added code for ubuntu 12 but don't have a setup so can't test. Could you try installing again? You can remove the service via https://github.com/hortonworks-gallery/ambari-zeppelin-service#remove-zeppelin-service

**Comment by Ngalstyan4** [comment]
I tried again and the error I was getting was indeed fixed and thanks for that!!
However, I encountered a new, seemingly more exotic, error
```sh
stderr:   /var/lib/ambari-agent/data/errors-1054.txt

2015-07-24 09:30:34,182 - Error while executing command 'install':
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 214, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/ZEPPELIN/package/scripts/master.py", line 91, in install
    Execute(service_packagedir + '/scripts/setup_snapshot.sh '+params.zeppelin_dir+' '+params.hive_server_host+' '+params.hive_metastore_host+' '+params.hive_metastore_port+' FIRSTLAUNCH ' + params.spark_jar + ' ' + params.zeppelin_host + ' ' + str(params.zeppelin_port) + ' '+ str(params.setup_view) + ' >> ' + params.zeppelin_log_file, user=params.zeppelin_user)
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 148, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 152, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 118, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 274, in action_run
    raise ex
Fail: Execution of '/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/ZEPPELIN/package/scripts/setup_snapshot.sh /opt/incubator-zeppelin ip-172-31-50-37.ec2.internal ip-172-31-50-37.ec2.internal 9083 FIRSTLAUNCH hdfs:///apps/zeppelin/zeppelin-spark-0.6.0-SNAPSHOT.jar ip-172-31-50-36.ec2.internal 9995 True >> /var/log/zeppelin/zeppelin-setup.log' returned 128. No directory, logging in with HOME=/
15/07/24 09:30:25 INFO fs.TrashPolicyDefault: Namenode trash configuration: Deletion interval = 360 minutes, Emptier interval = 0 minutes.
--2015-07-24 09:30:32--  https://www.dropbox.com/s/jlacnbvlzcdhjzf/notebooks.zip?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 108.160.172.206, 108.160.172.238
Connecting to www.dropbox.com (www.dropbox.com)|108.160.172.206|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://dl.dropboxusercontent.com/content_link/Qyblp6pqmFK6stE2lAMtzSKu84Qe4WKJYc8Wjsz7ib1PJKuW3XYYiHsIuPGCNwVN [following]
--2015-07-24 09:30:33--  https://dl.dropboxusercontent.com/content_link/Qyblp6pqmFK6stE2lAMtzSKu84Qe4WKJYc8Wjsz7ib1PJKuW3XYYiHsIuPGCNwVN
Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 54.225.184.81, 54.235.147.68, 54.235.161.178, ...
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|54.225.184.81|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9757 (9.5K) [application/zip]
Saving to: `notebooks.zip'


 0% [                                       ] 0           --.-K/s              
100%[======================================>] 9,757       --.-K/s   in 0s      

2015-07-24 09:30:34 (162 MB/s) - `notebooks.zip' saved [9757/9757]

fatal: could not create work tree dir 'iframe-view'.: Permission denied
stdout:   /var/lib/ambari-agent/data/output-1054.txt

2015-07-24 09:29:25,016 - u"Directory['/var/lib/ambari-agent/data/tmp/AMBARI-artifacts/']" {'recursive': True}
2015-07-24 09:29:25,226 - u"File['/var/lib/ambari-agent/data/tmp/AMBARI-artifacts//UnlimitedJCEPolicyJDK7.zip']" {'content': DownloadSource('http://ip-172-31-55-23.ec2.internal:8080/resources//UnlimitedJCEPolicyJDK7.zip')}
2015-07-24 09:29:25,326 - Not downloading the file from http://ip-172-31-55-23.ec2.internal:8080/resources//UnlimitedJCEPolicyJDK7.zip, because /var/lib/ambari-agent/data/tmp/UnlimitedJCEPolicyJDK7.zip already exists
2015-07-24 09:29:25,507 - u"Group['hadoop']" {'ignore_failures': False}
2015-07-24 09:29:25,509 - Modifying group hadoop
2015-07-24 09:29:25,601 - u"Group['users']" {'ignore_failures': False}
2015-07-24 09:29:25,602 - Modifying group users
2015-07-24 09:29:25,692 - u"Group['spark']" {'ignore_failures': False}
2015-07-24 09:29:25,693 - Modifying group spark
2015-07-24 09:29:25,783 - u"User['hive']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-07-24 09:29:25,784 - Modifying user hive
2015-07-24 09:29:25,835 - u"User['oozie']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'users']}
2015-07-24 09:29:25,836 - Modifying user oozie
2015-07-24 09:29:25,888 - u"User['ambari-qa']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'users']}
2015-07-24 09:29:25,888 - Modifying user ambari-qa
2015-07-24 09:29:25,940 - u"User['flume']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-07-24 09:29:25,940 - Modifying user flume
2015-07-24 09:29:25,992 - u"User['hdfs']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-07-24 09:29:25,993 - Modifying user hdfs
2015-07-24 09:29:26,044 - u"User['storm']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-07-24 09:29:26,044 - Modifying user storm
2015-07-24 09:29:26,096 - u"User['spark']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-07-24 09:29:26,096 - Modifying user spark
2015-07-24 09:29:26,147 - u"User['mapred']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-07-24 09:29:26,148 - Modifying user mapred
2015-07-24 09:29:26,199 - u"User['tez']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'users']}
2015-07-24 09:29:26,200 - Modifying user tez
2015-07-24 09:29:26,252 - u"User['zookeeper']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-07-24 09:29:26,253 - Modifying user zookeeper
2015-07-24 09:29:26,304 - u"User['falcon']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-07-24 09:29:26,305 - Modifying user falcon
2015-07-24 09:29:26,356 - u"User['yarn']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-07-24 09:29:26,357 - Modifying user yarn
2015-07-24 09:29:26,408 - u"User['hcat']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-07-24 09:29:26,409 - Modifying user hcat
2015-07-24 09:29:26,460 - u"User['ams']" {'gid': 'hadoop', 'ignore_failures': False, 'groups': [u'hadoop']}
2015-07-24 09:29:26,461 - Modifying user ams
2015-07-24 09:29:26,513 - u"File['/var/lib/ambari-agent/data/tmp/changeUid.sh']" {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2015-07-24 09:29:26,848 - u"Execute['/var/lib/ambari-agent/data/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa']" {'not_if': '(test $(id -u ambari-qa) -gt 1000) || (false)'}
2015-07-24 09:29:26,899 - Skipping u"Execute['/var/lib/ambari-agent/data/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa']" due to not_if
2015-07-24 09:29:26,900 - u"Group['hdfs']" {'ignore_failures': False}
2015-07-24 09:29:26,900 - Modifying group hdfs
2015-07-24 09:29:26,991 - u"User['hdfs']" {'ignore_failures': False, 'groups': [u'hadoop', 'hadoop', 'hdfs', u'hdfs']}
2015-07-24 09:29:26,992 - Modifying user hdfs
2015-07-24 09:29:27,044 - u"Directory['/etc/hadoop']" {'mode': 0755}
2015-07-24 09:29:27,228 - u"Directory['/etc/hadoop/conf.empty']" {'owner': 'root', 'group': 'hadoop', 'recursive': True}
2015-07-24 09:29:27,411 - u"Link['/etc/hadoop/conf']" {'not_if': 'ls /etc/hadoop/conf', 'to': '/etc/hadoop/conf.empty'}
2015-07-24 09:29:27,466 - Skipping u"Link['/etc/hadoop/conf']" due to not_if
2015-07-24 09:29:27,484 - u"File['/etc/hadoop/conf/hadoop-env.sh']" {'content': InlineTemplate(...), 'owner': 'hdfs', 'group': 'hadoop'}
2015-07-24 09:29:27,788 - u"Repository['HDP-2.2']" {'base_url': 'http://public-repo-1.hortonworks.com/HDP/ubuntu12/2.x/updates/2.2.6.3', 'action': ['create'], 'components': [u'HDP', 'main'], 'repo_template': 'repo_ubuntu.j2', 'repo_file_name': 'HDP', 'mirror_list': None}
2015-07-24 09:29:27,800 - u"File['/tmp/tmp6lM_aC']" {'content': 'deb http://public-repo-1.hortonworks.com/HDP/ubuntu12/2.x/updates/2.2.6.3 HDP main'}
2015-07-24 09:29:28,030 - Writing u"File['/tmp/tmp6lM_aC']" because contents don't match
2015-07-24 09:29:28,214 - u"Repository['HDP-UTILS-1.1.0.20']" {'base_url': 'http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.20/repos/ubuntu12', 'action': ['create'], 'components': [u'HDP-UTILS', 'main'], 'repo_template': 'repo_ubuntu.j2', 'repo_file_name': 'HDP-UTILS', 'mirror_list': None}
2015-07-24 09:29:28,219 - u"File['/tmp/tmpzifrNk']" {'content': 'deb http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.20/repos/ubuntu12 HDP-UTILS main'}
2015-07-24 09:29:28,421 - Writing u"File['/tmp/tmpzifrNk']" because contents don't match
2015-07-24 09:29:28,604 - u"Package['unzip']" {}
2015-07-24 09:29:28,695 - Skipping installing existent package unzip
2015-07-24 09:29:28,696 - u"Package['curl']" {}
2015-07-24 09:29:28,777 - Skipping installing existent package curl
2015-07-24 09:29:28,778 - u"Package['hdp-select']" {}
2015-07-24 09:29:28,870 - Skipping installing existent package hdp-select
2015-07-24 09:29:28,872 - u"Directory['/var/lib/ambari-agent/data/tmp/AMBARI-artifacts/']" {'recursive': True}
2015-07-24 09:29:29,054 - u"File['/var/lib/ambari-agent/data/tmp/AMBARI-artifacts//jdk-7u67-linux-x64.tar.gz']" {'content': DownloadSource('http://ip-172-31-55-23.ec2.internal:8080/resources//jdk-7u67-linux-x64.tar.gz')}
2015-07-24 09:29:29,155 - Not downloading the file from http://ip-172-31-55-23.ec2.internal:8080/resources//jdk-7u67-linux-x64.tar.gz, because /var/lib/ambari-agent/data/tmp/jdk-7u67-linux-x64.tar.gz already exists
2015-07-24 09:29:30,248 - u"Directory['/usr/jdk64']" {}
2015-07-24 09:29:30,431 - u"Execute['('chmod', 'a+x', u'/usr/jdk64')']" {'not_if': 'test -e /usr/jdk64/jdk1.7.0_67/bin/java', 'sudo': True}
2015-07-24 09:29:30,482 - Skipping u"Execute['('chmod', 'a+x', u'/usr/jdk64')']" due to not_if
2015-07-24 09:29:30,483 - u"Execute['mkdir -p /var/lib/ambari-agent/data/tmp/jdk && cd /var/lib/ambari-agent/data/tmp/jdk && tar -xf /var/lib/ambari-agent/data/tmp/AMBARI-artifacts//jdk-7u67-linux-x64.tar.gz && ambari-sudo.sh cp -rp /var/lib/ambari-agent/data/tmp/jdk/* /usr/jdk64']" {'not_if': 'test -e /usr/jdk64/jdk1.7.0_67/bin/java'}
2015-07-24 09:29:30,534 - Skipping u"Execute['mkdir -p /var/lib/ambari-agent/data/tmp/jdk && cd /var/lib/ambari-agent/data/tmp/jdk && tar -xf /var/lib/ambari-agent/data/tmp/AMBARI-artifacts//jdk-7u67-linux-x64.tar.gz && ambari-sudo.sh cp -rp /var/lib/ambari-agent/data/tmp/jdk/* /usr/jdk64']" due to not_if
2015-07-24 09:29:30,535 - u"Execute['('chgrp', '-R', u'hadoop', u'/usr/jdk64/jdk1.7.0_67')']" {'sudo': True}
2015-07-24 09:29:30,626 - u"Execute['('chown', '-R', 'root', u'/usr/jdk64/jdk1.7.0_67')']" {'sudo': True}
2015-07-24 09:29:30,965 - u"Execute['echo User selected spark_version:1.2']" {}
2015-07-24 09:29:31,047 - u'Execute[\'find /var/lib/ambari-agent/cache/stacks/HDP/2.2/services/ZEPPELIN/package -iname "*.sh" | xargs chmod +x\']' {}
2015-07-24 09:29:31,098 - u"Execute['hadoop fs -mkdir -p /user/zeppelin']" {'ignore_failures': True, 'user': 'hdfs'}
2015-07-24 09:29:35,360 - u"Execute['hadoop fs -chown zeppelin /user/zeppelin']" {'user': 'hdfs'}
2015-07-24 09:29:39,506 - u"Execute['hadoop fs -chgrp zeppelin /user/zeppelin']" {'user': 'hdfs'}
2015-07-24 09:29:43,569 - u"Execute['hadoop fs -mkdir -p hdfs:///apps/zeppelin']" {'ignore_failures': True, 'user': 'hdfs'}
2015-07-24 09:29:47,793 - u"Execute['hadoop fs -chown zeppelin hdfs:///apps/zeppelin']" {'user': 'hdfs'}
2015-07-24 09:29:51,940 - u"Execute['hadoop fs -chgrp zeppelin hdfs:///apps/zeppelin']" {'user': 'hdfs'}
2015-07-24 09:29:56,211 - u"Directory['/var/run/zeppelin-notebook']" {'owner': 'zeppelin', 'group': 'zeppelin', 'recursive': True}
2015-07-24 09:29:56,395 - u"Directory['/var/log/zeppelin']" {'owner': 'zeppelin', 'group': 'zeppelin', 'recursive': True}
2015-07-24 09:29:56,576 - u"Execute['touch /var/log/zeppelin/zeppelin-setup.log']" {'user': 'zeppelin'}
2015-07-24 09:29:56,685 - u"Execute['rm -rf /opt/incubator-zeppelin']" {'ignore_failures': True}
2015-07-24 09:29:56,857 - u"Execute['mkdir /opt/incubator-zeppelin']" {}
2015-07-24 09:29:56,909 - u"Execute['chown -R zeppelin:zeppelin /opt/incubator-zeppelin']" {}
2015-07-24 09:29:56,960 - u"Execute['echo Processing with zeppelin tar compiled with spark 1.2']" {}
2015-07-24 09:29:57,014 - u"Execute['echo Installing packages']" {}
2015-07-24 09:29:57,069 - u"Package['git']" {}
2015-07-24 09:29:57,157 - Skipping installing existent package git
2015-07-24 09:29:57,158 - u"Package['maven']" {}
2015-07-24 09:29:57,243 - Skipping installing existent package maven
2015-07-24 09:29:57,244 - u"Execute['tar -zxvf /tmp/zeppelin.tar.gz -C /opt/incubator-zeppelin >> /var/log/zeppelin/zeppelin-setup.log']" {'user': 'zeppelin'}
2015-07-24 09:30:03,409 - u"Execute['mv /opt/incubator-zeppelin/*/* /opt/incubator-zeppelin']" {'user': 'zeppelin'}
2015-07-24 09:30:03,519 - u"XmlConfig['zeppelin-site.xml']" {'owner': 'zeppelin', 'group': 'zeppelin', 'conf_dir': '/opt/incubator-zeppelin/conf', 'configurations': ...}
2015-07-24 09:30:03,539 - Generating config: /opt/incubator-zeppelin/conf/zeppelin-site.xml
2015-07-24 09:30:03,540 - u"File['/opt/incubator-zeppelin/conf/zeppelin-site.xml']" {'owner': 'zeppelin', 'content': InlineTemplate(...), 'group': 'zeppelin', 'mode': None, 'encoding': 'UTF-8'}
2015-07-24 09:30:03,767 - Writing u"File['/opt/incubator-zeppelin/conf/zeppelin-site.xml']" because contents don't match
2015-07-24 09:30:03,957 - u"File['/opt/incubator-zeppelin/conf/zeppelin-env.sh']" {'owner': 'zeppelin', 'content': InlineTemplate(...), 'group': 'zeppelin'}
2015-07-24 09:30:04,161 - Writing u"File['/opt/incubator-zeppelin/conf/zeppelin-env.sh']" because contents don't match
2015-07-24 09:30:04,345 - u"Execute['/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/ZEPPELIN/package/scripts/setup_snapshot.sh /opt/incubator-zeppelin ip-172-31-50-37.ec2.internal ip-172-31-50-37.ec2.internal 9083 CONFIGURE hdfs:///apps/zeppelin/zeppelin-spark-0.6.0-SNAPSHOT.jar ip-172-31-50-36.ec2.internal 9995 True >> /var/log/zeppelin/zeppelin-setup.log']" {'user': 'zeppelin'}
2015-07-24 09:30:21,899 - u"Execute['/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/ZEPPELIN/package/scripts/setup_snapshot.sh /opt/incubator-zeppelin ip-172-31-50-37.ec2.internal ip-172-31-50-37.ec2.internal 9083 FIRSTLAUNCH hdfs:///apps/zeppelin/zeppelin-spark-0.6.0-SNAPSHOT.jar ip-172-31-50-36.ec2.internal 9995 True >> /var/log/zeppelin/zeppelin-setup.log']" {'user': 'zeppelin'}
2015-07-24 09:30:34,182 - Error while executing command 'install':
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 214, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/ZEPPELIN/package/scripts/master.py", line 91, in install
    Execute(service_packagedir + '/scripts/setup_snapshot.sh '+params.zeppelin_dir+' '+params.hive_server_host+' '+params.hive_metastore_host+' '+params.hive_metastore_port+' FIRSTLAUNCH ' + params.spark_jar + ' ' + params.zeppelin_host + ' ' + str(params.zeppelin_port) + ' '+ str(params.setup_view) + ' >> ' + params.zeppelin_log_file, user=params.zeppelin_user)
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 148, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 152, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 118, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 274, in action_run
    raise ex
Fail: Execution of '/var/lib/ambari-agent/cache/stacks/HDP/2.2/services/ZEPPELIN/package/scripts/setup_snapshot.sh /opt/incubator-zeppelin ip-172-31-50-37.ec2.internal ip-172-31-50-37.ec2.internal 9083 FIRSTLAUNCH hdfs:///apps/zeppelin/zeppelin-spark-0.6.0-SNAPSHOT.jar ip-172-31-50-36.ec2.internal 9995 True >> /var/log/zeppelin/zeppelin-setup.log' returned 128. No directory, logging in with HOME=/
15/07/24 09:30:25 INFO fs.TrashPolicyDefault: Namenode trash configuration: Deletion interval = 360 minutes, Emptier interval = 0 minutes.
--2015-07-24 09:30:32--  https://www.dropbox.com/s/jlacnbvlzcdhjzf/notebooks.zip?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 108.160.172.206, 108.160.172.238
Connecting to www.dropbox.com (www.dropbox.com)|108.160.172.206|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://dl.dropboxusercontent.com/content_link/Qyblp6pqmFK6stE2lAMtzSKu84Qe4WKJYc8Wjsz7ib1PJKuW3XYYiHsIuPGCNwVN [following]
--2015-07-24 09:30:33--  https://dl.dropboxusercontent.com/content_link/Qyblp6pqmFK6stE2lAMtzSKu84Qe4WKJYc8Wjsz7ib1PJKuW3XYYiHsIuPGCNwVN
Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 54.225.184.81, 54.235.147.68, 54.235.161.178, ...
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|54.225.184.81|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9757 (9.5K) [application/zip]
Saving to: `notebooks.zip'


 0% [                                       ] 0           --.-K/s              
100%[======================================>] 9,757       --.-K/s   in 0s      

2015-07-24 09:30:34 (162 MB/s) - `notebooks.zip' saved [9757/9757]

fatal: could not create work tree dir 'iframe-view'.: Permission denied



```

You can see the error in the last file
I attached the whole log file to make it clear for you when exactly does the error occur

Thanks for the effort anyway and I hope this will help to find a solution and make ZEPPELIN and even better tool to work with.

I look forward to hearing from you!!

Narek

**Comment by abajwa-hw** [comment]
Looks like it wasn't able to create /tmp/iframe-view dir for some reason? Perhaps you can try removing those dirs and re-installing the latest version of the service?
rm -rf /tmp/iframe*
rm -rf /tmp/zeppelin*

Thanks
Ali
