### ISSUE TITLE
zeppelin 0.6.0 integration 

### ISSUE THREAD

**Issue by trungtv** [hortonworks-gallery/ambari-zeppelin-service#21]
Hello, 
is there any ways to deploy the latest version of zeppelin with this plugin? I scan the code and it doesn't seem to be obvious.

**Comment by webstergd** [comment]
I have the same trouble with identifying how to compile with the 0.6-snapshop. I would also love an option to specify the spark profile i.e. -Pcassandra-spark-1.5. 

Any help would be much appreciated.

**Comment by abajwa-hw** [comment]
This is usually how I compile
https://gist.github.com/randerzander/5c6ca7bdd06876c9b247


Sent from my iPhone

On Apr 16, 2016, at 4:03 AM, webstergd <notifications@github.com<mailto:notifications@github.com>> wrote:


I have the same trouble with identifying how to compile with the 0.6-snapshop. I would also love an option to specify the spark profile i.e. -Pcassandra-spark-1.5.

Any help would be much appreciated.

-

**Comment by webstergd** [comment]
Pretty useful, thanks. I seem to have everything mostly working but I am running into I believe a dependency conflict with guava. Have you seen this error before? Happens if you do say an RDD.count()

WARN [2016-04-18 14:16:05,212] ({task-result-getter-2} Logging.scala[logWarning]:70) - Lost task 1.3 in stage 0.0 (TID 10, vm-10-155-208-69.cloud.mwn.de): java.io.IOException: Failed to open native conne
ction to Cassandra at {10.0.4.80, 10.0.4.81, 10.0.4.82}:9042
        at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:162)
        at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$2.apply(CassandraConnector.scala:148)
        at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$2.apply(CassandraConnector.scala:148)
        at com.datastax.spark.connector.cql.RefCountedCache.createNewValueAndKeys(RefCountedCache.scala:31)
        at com.datastax.spark.connector.cql.RefCountedCache.acquire(RefCountedCache.scala:56)
        at com.datastax.spark.connector.cql.CassandraConnector.openSession(CassandraConnector.scala:81)
        at com.datastax.spark.connector.rdd.CassandraTableScanRDD.compute(CassandraTableScanRDD.scala:218)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.Futures.withFallback(Lcom/google/common/util/concurrent/ListenableFuture;Lcom/google/common/util/concurrent/FutureFallback;Ljava/u
til/concurrent/Executor;)Lcom/google/common/util/concurrent/ListenableFuture;
        at com.datastax.driver.core.Connection.initAsync(Connection.java:177)
        at com.datastax.driver.core.Connection$Factory.open(Connection.java:731)
        at com.datastax.driver.core.ControlConnection.tryConnect(ControlConnection.java:251)
        at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:199)
        at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:77)
        at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1414)
        at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:393)
        at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:155)
        ... 14 more
