### ISSUE TITLE
Local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by vishalvpv** [hortonworks-gallery/ambari-zeppelin-service#30]
File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/ZEPPELIN/package/scripts/master.py", line 230, in post_request  

jsonresp = json.loads(response.decode('utf-8'))
UnboundLocalError: local variable 'response' referenced before assignment

Above assignment should only be done if exception does not occur.

**Comment by appym** [comment]
I get the same issue

```bash
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/ZEPPELIN/package/scripts/master.py", line 234, in <module>
    Master().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 219, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/ZEPPELIN/package/scripts/master.py", line 178, in start
    self.update_zeppelin_interpreter()
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/ZEPPELIN/package/scripts/master.py", line 210, in update_zeppelin_interpreter
    self.post_request(zeppelin_int_url + hivebody['id'], hivebody)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/ZEPPELIN/package/scripts/master.py", line 229, in post_request
    jsonresp = json.loads(response.decode('utf-8'))
UnboundLocalError: local variable 'response' referenced before assignment
```

**Comment by appym** [comment]
I manually made the code change suggested here and then restarted the ambari-server to make it work.
https://github.com/hortonworks-gallery/ambari-zeppelin-service/pull/28/commits/ec4428c4236fea39858ccc509e6f198520518af7
